//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtosProjectModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string NamePerson { get; set; }
        public int Fk_Person { get; set; }
    
        public virtual Person Person1 { get; set; }
        public virtual Person Person2 { get; set; }
    }
}
